version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - go mod download

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - flags:
      - -trimpath
      - -a
      - -tags=eminmuhammadi.com/emx
    env:
      - CGO_ENABLED=0
    gcflags:
      - all=-trimpath={{.Env.HOME}}
      - -N
      - -l
    asmflags:
      - all=-trimpath={{.Env.HOME}}
    ldflags:
      - -s
      - -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"

universal_binaries:
  - replace: false

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
