version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - go mod download

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - gobinary: garble
    command: "-literals"
    flags: ["-tiny", "-seed=random", "build"]
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
    env:
      - CGO_ENABLED=0
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
      - -N 
      - -l
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - -s
      - -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"

universal_binaries:
  - replace: false

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
