on:
  push:
    paths:
      - "**/**/*.go"
      - "**/*.go"
      - "*.go"
  pull_request:
    paths:
      - "**/**/*.go"
      - "**/*.go"
      - "*.go"

name: Lint

jobs:
  lint:
    name: Lint files
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  test:
    name: Run tests
    runs-on: "ubuntu-latest"
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
      - run: go test -v -cover
